
spring:
    profiles.active: dev
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    output:
        ansi.enabled: always
    jackson.time-zone: Asia/Seoul
    config:
        import: .env.properties
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    jackson:
        serialization: 
            FAIL_ON_EMPTY_BEANS: false

# mybatis:
#     type-aliases-package:
#     mapper-locations: classpath*:mapper/*Mapper.xml